info:
  version: 1.0.7
  title: Weather events
  name: weather-events
  summary: Events from the Weather Company API
  contact:
    name: Dale Lane
    email: dalelane@acmeweather.com
    url: 'https://acme-weather.com'
  termsOfService: 'https://acme-weather.com/tos.html'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
gateways:
  - event-gateway
plans:
  default-plan:
    title: Default Plan
    description: Default Plan
    rate-limits:
      default:
        value: 100/1hour
    apis:
      ibmuklocations0.0.9: {}
      ibmuslocations0.9.1: {}
apis:
  ibmuklocations0.0.9:
    $ref: ibmuklocations_0.0.9.yaml
  ibmuslocations0.9.1:
    $ref: ibmuslocations_0.9.1.yaml
visibility:
  view:
    type: public
    orgs: []
    tags: []
    enabled: true
  subscribe:
    type: authenticated
    orgs: []
    tags: []
    enabled: true
product: 1.0.0
